// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Application struct {
	ID   string  `json:"id"`
	Name *string `json:"name"`
}

type Device struct {
	ID      string  `json:"id"`
	Name    *string `json:"name"`
	SimCard *string `json:"simCard"`
}

type Enterprise struct {
	ID           string         `json:"id"`
	Name         *string        `json:"name"`
	Description  *string        `json:"description"`
	Applications []*Application `json:"applications"`
	Sites        []*Site        `json:"sites"`
}

type SimCard struct {
	ID   string  `json:"id"`
	Name *string `json:"name"`
}

type Site struct {
	ID            string     `json:"id"`
	Name          *string    `json:"name"`
	Devices       []*Device  `json:"devices"`
	SimCards      []*SimCard `json:"simCards"`
	SimCardsCount int        `json:"simCardsCount"`
	Alerts        *int       `json:"alerts"`
	Image         *string    `json:"image"`
	Slices        []*Slices  `json:"slices"`
}

type Slices struct {
	ID   string  `json:"id"`
	Name *string `json:"name"`
}
